// homewend — Copyright (C) 2026 Ron Alder
// SPDX-License-Identifier: AGPL-3.0-or-later

// Every sentence the window shows a person. A second language is a second
// table with the same keys.
export const text = {
	brand: 'Homewend',
	menu: 'Show or hide the sidebar',
	importFolder: 'Import a folder',

	signInTitle: 'Google Photos,\non your own disk.',
	signInLead:
		'No zips to babysit, no download to restart by hand. Plain folders, sorted by date and album, and nothing passes through our servers.',
	signInCall: 'Bring your photos home.',
	signInCallSub: 'One sign-in, and Homewend does the rest.',
	signInButton: 'Sign in to Google',
	signInWaiting: 'Waiting for Google',
	stepSignIn: 'Sign in',
	stepSignInDesc: 'Homewend never sees your password.',
	stepChoose: 'Choose',
	stepChooseDesc: 'Everything, a year, or a takeout you made.',
	stepBringHome: 'Bring home',
	stepBringHomeDesc: 'Homewend does the rest.',

	allPhotos: 'All photos',
	noDate: 'No date',
	photosAndVideos: (n: number) => `${n.toLocaleString('en')} photos and videos`,
	noPhotos: 'No photos yet',
	noPhotosDesc: 'They appear here as each part of the takeout arrives.',
	seeDownload: 'See the download',
	signingIn: 'Sign in in the browser window that opened, then come back here.',
	years: 'YEARS',
	albums: 'ALBUMS',
	takeouts: 'Takeouts',
	settings: 'Settings',
	more: (n: number) => `${n} more`,
	fewer: 'Show fewer',
	showAccount: (name: string) => `Show ${name}'s photos`,

	settingsTitle: 'Settings',
	appearance: 'APPEARANCE',
	theme: 'Theme',
	themeDesc: "System follows your computer's light or dark mode.",
	themeSystem: 'System',
	themeLight: 'Light',
	themeDark: 'Dark',

	chooseTitle: 'What should Homewend bring home?',
	chooseLead: "Google prepares the takeout, and that can take hours. You don't have to wait here.",
	everything: 'Everything.',
	everythingDesc: 'All your photos and videos, every album. The first time, this is the one.',
	oneYear: 'One year.',
	olderYear: 'More',
	oneYearDesc: 'Smaller and faster. A good way to try Homewend first.',
	oneAsked: 'One you asked for.',
	oneAskedDesc: 'Already made a takeout yourself on Google? Pick it from the list and Homewend downloads it.',
	seeTakeouts: 'See your takeouts',
	photosGoTo: 'Photos go to',
	change: 'Change…',
	chooseFolder: 'Choose a folder',
	startEverything: 'Start a takeout of everything',
	startYear: (y: number) => `Start a takeout of ${y}`,
	noLibraryYet: 'Choose where your photos go first.',
	free: (n: string) => `${n} free`,
	notifyWhenReady: "You'll get a notification when it's ready.",
	left: (s: string) => `${s} left`,
	bringHome: 'Bring your photos home',

	bringingTitle: 'Bringing your photos home.',
	bringingLead: 'You can close this window. If the computer sleeps, Homewend picks up at the same byte.',
	preparingTitle: 'Google is preparing\nall your photos.',
	preparingLead: "This often takes hours. The download starts by itself as soon as it's ready, and Google also sends you an email.",
	pausedTitle: 'Paused.',
	pausedLead: 'Nothing is lost: Homewend picks up at the same byte when you resume.',
	finishedTitle: 'Your photos are home.',
	byYear: 'By year.',
	byYearLegend: 'arrived / in the takeout',
	waitingForGoogle: 'Waiting for Google',
	downloadingPart: (n: number, of: number) => `Downloading part ${n} of ${of}`,
	bringingPart: (n: number, of: number) => `Bringing home part ${n} of ${of}`,
	pausedAt: (n: number, of: number) => `Paused at part ${n} of ${of}`,
	checking: 'Checking with Google',
	sorting: 'Sorting what arrived',
	gbOf: (done: string, total: string) => `${done} of ${total}`,
	details: 'Details',
	pause: 'Pause',
	resume: 'Resume',
	retrying: (why: string) => `No network: trying again (${why})`,
	failed: 'Stopped',
	seeLibrary: 'See them in your library',
	downloaded: 'downloaded',
	inFolder: 'photos in your folder',
	leftAtSpeed: 'left at this speed',
	aboutTime: (s: string) => `about ${s}`,

	takeoutsTitle: 'Takeouts',
	takeoutCol: 'HOLDS',
	askedCol: 'ASKED',
	sizeCol: 'SIZE',
	statusCol: 'STATUS',
	holdsAll: 'All photos',
	holdsYear: (y: number) => String(y),
	// Google does not say what a takeout holds: only those Homewend asked for
	// are known.
	holdsUnknown: 'Not known',
	parts: (n: number) => `${n} parts`,
	statusPreparing: 'Google is preparing',
	statusReady: 'Ready',
	statusExpired: 'Expired',
	statusDownloading: 'Downloading',
	since: (d: string) => `Since ${d}`,
	until: (d: string) => `Until ${d}`,
	download: 'Download',
	newTakeout: 'New takeout',
	readingTakeouts: 'Reading your takeouts from Google…',
	noTakeouts: 'No takeouts on Google yet.',
	unknownNote:
		"Not known: a takeout made on Google, not by Homewend. Google doesn't say whether it holds everything or one year.",

	library: 'LIBRARY',
	whereTheyGo: 'Where your photos go',
	privacy: 'PRIVACY',
	googleCookies: 'Google cookies',
	googleCookiesDesc:
		'Homewend keeps the Google cookies of each account in a browser profile of its own, on this computer. Purging them signs Homewend out of that account only; its photos stay where they are.',
	purge: 'Purge cookies',
	addAccount: 'Add a Google account',
	about: 'ABOUT',
	aboutDesc: 'Open source, AGPL-3.0. Nothing passes through our servers.',
	sourceCode: 'Source code',
	upcoming: 'Upcoming',
	importTitle: 'Import a folder',
	importDesc:
		'Photos already on a disk or an old backup go into this same library, by date and album. Homewend tells you which ones were already here.',
	close: 'Close',
	copyFolderPath: 'Copy folder path',
	pickUpAfterSleep: 'Picks up by itself after sleep',
	taken: (d: string) => `Taken ${d}`,
	noDateSub: (n: string) => `${n} photos and videos with no date: neither Google nor the photo says when it was taken`,
	openInFolder: /Mac/.test(globalThis.navigator?.platform ?? '')
		? 'Open in Finder'
		: /Win/.test(globalThis.navigator?.platform ?? '')
			? 'Show in Explorer'
			: 'Open folder',
	previous: 'Previous',
	next: 'Next',

	bannerPassword: (who: string) => `Google asks for the password of ${who} once more.`,
	bannerPasswordDesc: 'Type it in the window that opened. It is needed once for this account, and the window closes by itself.',
	bannerSignedOut: (who: string) => `Google signed out ${who}.`,
	bannerSignedOutDesc: (part: number) => `Sign in again and Homewend carries on from part ${part}. Nothing already downloaded is lost.`,
	signInAgain: 'Sign in again',
	bannerNoSpace: 'Not enough space on this disk.',
	bannerNoSpaceDesc: (need: string, free: string) => `The takeout needs ${need} and the disk has ${free} free. Free some space, or choose another folder.`,
	chooseAnotherFolder: 'Choose another folder',
	bannerExpired: (who: string) => `Google no longer offers this takeout of ${who}.`,
	bannerExpiredDesc: 'Google keeps a takeout for 7 days. The photos already here stay; a new takeout brings home the rest.',
	newTakeoutAction: 'New takeout',
	bannerNetwork: 'Waiting for the network.',
	bannerNetworkDesc: 'Homewend tries again by itself every minute. The bytes already downloaded are kept.',
	bannerFinished: (who: string, n: string) => `${who}'s ${n} photos and videos are home.`,
	bannerFinishedDesc: (dir: string) => `Every file in the takeout is in ${dir}, by year and by album.`,
	openLibrary: 'Open the library',
	notifyFinished: 'Your photos are home',
	notifyFinishedBody: (n: string, who: string) => `${n} photos and videos of ${who}, by year and album.`,
	notifyPasswordBody: (who: string) => `Once, for ${who}: type it in the window that opened.`,
	notifySignedOut: 'Google signed you out',
	notifySignedOutBody: (who: string) => `Sign in again to finish the takeout of ${who}.`,
	notifyReady: 'Your takeout is ready',
	notifyReadyBody: (who: string) => `${who}'s photos are coming down now.`,
	notifyPassword: 'Google asks for your password',

	askedToday: 'asked today',
	asked: 'asked',
	lastLooked: 'last looked',
	keepsOnceReady: 'Google keeps it, once ready',
	sevenDays: '7 days',
	minAgo: (n: number) => (n < 1 ? 'just now' : `${n} min ago`),
	canClose: 'You can close Homewend.',
	canCloseDesc:
		'It keeps going in the background and picks up where it was after a restart. It never asks Google twice.',
	stepPrepares: 'Google prepares the takeout',
	stepDownloads: 'Homewend downloads it, part by part',
	stepLands: 'Your photos land in your folder, counted',
	stepNotify: 'You get a notification',
	seeOnTakeout: 'See it on Google Takeout',
	firstArrived: 'The first photos that arrived, exactly as Google sent them.',
	lastArrived: 'Last arrived, exactly as Google sent them.',
	stillSorting: 'Still sorting',
	stillSortingDesc: 'They find their year when the rest arrives',
	keepsUntil: 'Google keeps the takeout until',
	allHere: 'all here',
	missing: (n: string) => `${n} missing from the takeout`,
	arriving: 'arriving with the next parts'
} as const;
