// homewend — Copyright (C) 2026 Ron Alder
// SPDX-License-Identifier: AGPL-3.0-or-later

// Every sentence the window shows a person. A second language is a second
// table with the same keys.
export const text = {
	brand: 'Homewend',
	menu: 'Show or hide the sidebar',
	importFolder: 'Import a folder',

	signInTitle: 'Google Photos,\non your own disk.',
	signInLead:
		'No zips to babysit, no download to restart by hand. Plain folders, sorted by date and album, and nothing passes through our servers.',
	signInCall: 'Bring your photos home.',
	signInCallSub: 'One sign-in, and Homewend does the rest.',
	signInButton: 'Sign in to Google',
	signInWaiting: 'Waiting for Google',
	stepSignIn: 'Sign in',
	stepSignInDesc: 'Homewend never sees your password.',
	stepChoose: 'Choose',
	stepChooseDesc: 'Everything, a year, or a takeout you made.',
	stepBringHome: 'Bring home',
	stepBringHomeDesc: 'Homewend does the rest.',

	allPhotos: 'All photos',
	noDate: 'No date',
	photosAndVideos: (n: number) => `${n.toLocaleString('en')} photos and videos`,
	noPhotos: 'No photos yet',
	noPhotosDesc: 'They appear here as each part of the takeout arrives.',
	seeDownload: 'See the download',
	signingIn: 'Sign in in the browser window that opened, then come back here.',
	years: 'YEARS',
	albums: 'ALBUMS',
	takeouts: 'Takeouts',
	settings: 'Settings',
	more: (n: number) => `${n} more`,
	fewer: 'Show fewer',
	showAccount: (name: string) => `Show ${name}'s photos`,

	settingsTitle: 'Settings',
	appearance: 'APPEARANCE',
	theme: 'Theme',
	themeDesc: "System follows your computer's light or dark mode.",
	themeSystem: 'System',
	themeLight: 'Light',
	themeDark: 'Dark',

	chooseTitle: 'What should Homewend bring home?',
	chooseLead: "Google prepares the takeout, and that can take hours. You don't have to wait here.",
	everything: 'Everything.',
	everythingDesc: 'All your photos and videos, every album. The first time, this is the one.',
	oneYear: 'One year.',
	oneYearDesc: 'Smaller and faster. A good way to try Homewend first.',
	oneAsked: 'One you asked for.',
	oneAskedDesc: 'Already made a takeout yourself on Google? Pick it from the list and Homewend downloads it.',
	seeTakeouts: 'See your takeouts',
	photosGoTo: 'Photos go to',
	change: 'Change…',
	chooseFolder: 'Choose a folder',
	startEverything: 'Start a takeout of everything',
	startYear: (y: number) => `Start a takeout of ${y}`,
	noLibraryYet: 'Choose where your photos go first.',
	bringHome: 'Bring your photos home',

	bringingTitle: 'Bringing your photos home.',
	bringingLead: 'You can close this window. If the computer sleeps, Homewend picks up at the same byte.',
	preparingTitle: 'Google is preparing\nall your photos.',
	preparingLead: "This often takes hours. The download starts by itself as soon as it's ready, and Google also sends you an email.",
	pausedTitle: 'Paused.',
	pausedLead: 'Nothing is lost: Homewend picks up at the same byte when you resume.',
	finishedTitle: 'Your photos are home.',
	byYear: 'By year.',
	byYearLegend: 'arrived / in the takeout',
	waitingForGoogle: 'Waiting for Google',
	downloadingPart: (n: number, of: number) => `Downloading part ${n} of ${of}`,
	bringingPart: (n: number, of: number) => `Bringing home part ${n} of ${of}`,
	pausedAt: (n: number, of: number) => `Paused at part ${n} of ${of}`,
	checking: 'Checking with Google',
	sorting: 'Sorting what arrived',
	gbOf: (done: string, total: string) => `${done} of ${total}`,
	details: 'Details',
	pause: 'Pause',
	resume: 'Resume',
	retrying: (why: string) => `No network: trying again (${why})`,
	failed: 'Stopped',
	seeLibrary: 'See them in your library',

	takeoutsTitle: 'Takeouts',
	takeoutCol: 'TAKEOUT',
	askedCol: 'ASKED',
	sizeCol: 'SIZE',
	statusCol: 'STATUS',
	holdsAll: 'All photos',
	holdsYear: (y: number) => String(y),
	holdsUnknown: 'Unknown',
	parts: (n: number) => `${n} parts`,
	statusPreparing: 'Google is preparing',
	statusReady: 'Ready',
	statusExpired: 'Expired',
	until: (d: string) => `Until ${d}`,
	download: 'Download',
	newTakeout: 'New takeout',
	readingTakeouts: 'Reading your takeouts from Google…',
	noTakeouts: 'No takeouts on Google yet.'
} as const;
