// homewend — Copyright (C) 2026 Ron Alder
// SPDX-License-Identifier: AGPL-3.0-or-later

// Writes src/lib/tokens.css from tokens.json, the variables exported from the
// design file. The design is the source: change it there, export again, and
// this script turns it into CSS custom properties; never edit the CSS.
import { readFileSync, writeFileSync } from 'node:fs';

const { variables } = JSON.parse(readFileSync(new URL('../tokens.json', import.meta.url)));

// Fonts are named after the packages that ship them, with the system's as
// the fallback for the instant before they load.
const fonts = {
	Inter: "'Inter Variable', system-ui, sans-serif",
	'JetBrains Mono': "'JetBrains Mono', ui-monospace, monospace"
};

function value(v) {
	if (v.type === 'number') return `${v.value}px`;
	if (v.type === 'string') return fonts[v.value] ?? v.value;
	return v.value;
}

const light = [];
const dark = [];
for (const [name, v] of Object.entries(variables)) {
	if (!Array.isArray(v.value)) {
		light.push(`\t--${name}: ${value(v)};`);
		continue;
	}
	for (const entry of v.value) {
		const line = `\t--${name}: ${value({ ...v, value: entry.value })};`;
		(entry.theme.mode === 'dark' ? dark : light).push(line);
	}
}

const css = `/* Generated by scripts/tokens.js from tokens.json. Do not edit. */
:root {
\tcolor-scheme: light dark;
${light.join('\n')}
}
@media (prefers-color-scheme: dark) {
\t:root {
${dark.map((l) => '\t' + l).join('\n')}
\t}
}
`;
writeFileSync(new URL('../src/lib/tokens.css', import.meta.url), css);
